const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto'),{spawnSync}=require('node:child_process');
const repo=path.resolve(__dirname,'../..'),dir=__dirname,head='c5038e8c1f55875d9a87b0409a35e2af1d1bd9a5';
const git=(...args)=>{const r=spawnSync('git',args,{cwd:repo,encoding:'utf8',windowsHide:true});assert.equal(r.status,0,r.stderr);return r.stdout.trim();};
const digest=bytes=>crypto.createHash('sha256').update(bytes).digest('hex'),hash=file=>digest(fs.readFileSync(file));
const read=file=>{const b=fs.readFileSync(file);return b[0]===255&&b[1]===254?b.subarray(2).toString('utf16le'):b.toString('utf8').replace(/^\uFEFF/,'');};
const load=file=>JSON.parse(read(file));
const common=git('rev-parse','--path-format=absolute','--git-common-dir');
const checks=[];
for(const [name,root,count,additional] of [
 ['native-source','wa-native-browser-Xrqseo',101,0],['native-embedded','wa-native-browser-D1t1J7',101,0],
 ['matrix-source','wa-native-browser-Tsnh3C',76,50],['matrix-embedded','wa-native-browser-PgENBA',76,54],['recovery','wa-two-window-vRnBeW',22,0]
]){
 const file=path.join(common,'wa-recovery-evidence',root,'report.json'),r=load(file);
 assert.ok(r.passed);assert.equal(r.checks.length,count);if(additional){assert.equal(r.review.cases.length,additional);assert.equal(r.review.failures.length,0);assert.ok(r.review.cases.every(c=>c.passed));}
 assert.ok(r.cleanup.fixture_home_removed&&r.cleanup.browserClosed&&r.cleanup.ownedPids.every(p=>p.exited&&p.job.creation_proven&&p.job.assigned&&p.job.in_job&&p.job.kill_on_close&&p.job.no_breakaway&&p.job.limit_flags===8192&&p.job.drained&&p.job.accounting.active_processes===0));
 fs.writeFileSync(path.join(dir,name+'.receipt.json'),JSON.stringify(r,null,2)+'\n');
 checks.push({name,passed:true,originalAssertions:count,additionalReviewCases:additional,skipped:0,raw:file,rawHash:hash(file),binary:r.binary,lua:r.lua,cleanupVerified:true});
}
const controls=load(path.join(dir,'causal-controls.json'));assert.equal(controls.length,4);
for(const control of controls){const r=load(control.receipt);assert.ok(control.intended&&control.exit===1&&r.review.failures.includes(control.expected));assert.ok(r.cleanup.fixture_home_removed&&r.cleanup.ownedPids.every(p=>p.exited&&p.job.in_job&&p.job.kill_on_close&&p.job.no_breakaway&&p.job.drained&&p.job.accounting.active_processes===0));control.receiptHash=hash(control.receipt);control.logHash=hash(path.join(dir,control.name+'.log'));}
const build=load(path.join(dir,'build.json'));require(path.join(repo,'scripts/native-child-build-proof.cjs')).verify(repo,build.binary,path.join(dir,'build.json'));
const uiJob=load(path.join(dir,'ui-job.json'));assert.ok(uiJob.creation_proven&&uiJob.assigned&&uiJob.in_job&&uiJob.kill_on_close&&uiJob.no_breakaway&&uiJob.drained&&uiJob.accounting.active_processes===0&&uiJob.native_exit===0);
assert.ok(read(path.join(dir,'ui.log')).includes('[stages: reload,startup-recovery,inspect-window,view-window]'));
git('diff','--exit-code',head,'--','ui','lua','rust','scripts');git('diff','--exit-code','fd4b521','--','review/original-native-ui');
const sourceInstrument=git('show','6b3aeba:review/native-ui-successor/probe.cjs')+'\n';
fs.writeFileSync(path.join(dir,'source-matrix-instrument.cjs'),sourceInstrument);
const packet=path.join(common,'wa-original-ui-repair','ctx_4c7b6e9b1ae8','report.json'),producer=load(packet);
assert.equal(producer.head,head);assert.equal(git('rev-parse',head+'^{tree}'),producer.tree);
for(const [file,expected] of Object.entries(producer.sources))assert.equal(hash(path.join(repo,file)),expected,file);
const producerMutations=producer.mutations.checks.map(m=>{assert.ok(read(m.log.path).includes(m.assertion));assert.equal(hash(m.log.path),m.log.sha256);return {name:m.name,assertion:m.assertion,exit:m.exit,raw:m.log.path,rawHash:m.log.sha256};});
const report={schema:1,kind:'independent-exact-successor-source-review-not-admission',verdict:'original_findings_resolved',requestChanges:false,scope:'The two original18 findings and connected native fallback/cursor/identity regressions; later Root chat-control changes are excluded',producer:{head,tree:producer.tree,parent:producer.parent,packet,packetHash:hash(packet)},review:{branch:git('branch','--show-current'),custodyMerge:git('rev-parse','HEAD'),custodyTree:git('rev-parse','HEAD^{tree}'),originMain:git('rev-parse','origin/main'),behind:Number(git('rev-list','--count','HEAD..origin/main')),mergeTree:git('merge-tree','--write-tree','origin/main','HEAD'),session:process.env.CODEX_THREAD_ID,terminal:'term_3f65c45a-b412-41ed-b814-5b3ca0f95894',task:'task_970828440678',dispatch:'ctx_8a67cfaf05c9',sourceChanged:false,originalReviewUnchanged:true},build:{binary:build.binary,sha256:build.binary_sha256,receipt:'build.json',jobs:2,binding:'actual caller-attested cargo source hashes before/after build plus final verification; not binary introspection'},checks,directUi:{passed:true,stages:['reload','startup-recovery','inspect-window','view-window'],job:uiJob,log:'ui.log'},independentCausalControls:controls,producerCausalRawLogsInspected:producerMutations,
 originalControls:{review:'../original-native-ui/report.json',reviewCommit:'fd4b521e41f886ffb7fdef48108bde9c3f36a876',preparedMatrixCommit:'6b3aeba',originalSource:'18bc6bf05be9cdbd01a1e50a6a520e0e9e9a499b',originalRecovery503:'../original-native-ui/recovery-initial.receipt.json',originalFailureControlReused:true,repeatedBroadOriginalSuiteDuringPreparation:false},
 instruments:{sourceMatrix:{commit:'6b3aeba',path:'source-matrix-instrument.cjs',hash:digest(sourceInstrument),cases:50},strengthenedMatrix:{path:'probe.cjs',hash:hash(path.join(dir,'probe.cjs')),cases:54},immutableNativeTemplate:{commit:'18bc6bf05be9cdbd01a1e50a6a520e0e9e9a499b',file:'scripts/test-native-child-browser.cjs'}},
 admission:{authored:false,gateVerified:false,sourceAcceptanceAuthored:false,soleLane:'ctx_50a3da02dcf1',currentRequirementReportedByRoot:'full_required for original18 plus runtime footprint; focused source review is not admission; known inherited harness fixes belong separate exact combined gate',unreviewedHarnessImported:false},publication:{producerPush:false,reviewBranchPush:false,reason:'remote.main_only=true; local branch is deliverable',mainMoved:false,deployed:false},
 limits:['The original review folder/source ancestry remain unchanged; this new folder contains successor evidence. Private build target was reused, so original binary receipts retain historical hashes while current candidate has its own source binding.','Source matrix50 ran before strengthening; embedded matrix54 adds explicit retained raw DOM/fold/anchor and full original terminal content checks. Their exact instruments are distinguished rather than counting 54 for both.','A terminal gap retains separately labelled partial live output and complete stored messages. Text can overlap between those sources, but known raw DOM identities and the final durable message are not replayed or duplicated. No complete raw history reconstruction is claimed.','Restoration proves retained known DOM and the original first256 archive page; it does not prove all archived history through power loss or compare every archived page after restart.','Raw unavailable errors become named gaps; owner/session/node/attempt/epoch/cursor refusals do not grant fallback. JSON null remains absent through the unchanged decoder, not a new cursor contract.','The strengthened embedded matrix matched the full terminal content to the actual original; no production resource/account/provider/node/window or paid inference was used.','No new Rust tests were repeated: correction changes only Lua/UI/test code, and original selected20 native +2 journal +36 high-ID HTTP receipts remain historical proof, not admission for this combined tree.','Producer graph audit timed out and was positively drained; no completed graph omission audit or correctness certificate is claimed. Manual connected source/callers were inspected.','FULL synchronous journal writes, unbounded durable events and full materialized history costs are inherited; no performance or retention default is endorsed.','Later Root background completion/read-capacity and failed-task continuation changes remain separate. Full application gate/admission/main/deploy remain sole merge-lane work.']};
for(const ancestor of [head,'18bc6bf','98e14c5','fd4b521','6b3aeba'])assert.equal(spawnSync('git',['merge-base','--is-ancestor',ancestor,'HEAD'],{cwd:repo}).status,0,ancestor);
fs.writeFileSync(path.join(dir,'report.json'),JSON.stringify(report,null,2)+'\n');
for(const name of fs.readdirSync(dir))if(/\.(json|log|cjs|md)$/.test(name)){const file=path.join(dir,name);fs.writeFileSync(file,read(file).replace(/\r\n/g,'\n'),'utf8');}
console.log('Exact successor independent scoped source report assembled; receipt/source/cleanup invariants verified');
