const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict'),{spawnSync}=require('node:child_process');
const repo=path.resolve(__dirname,'../..'),dir=__dirname;
const git=(...args)=>{const r=spawnSync('git',args,{cwd:repo,encoding:'utf8',windowsHide:true});assert.equal(r.status,0,r.stderr);return r.stdout.trim();};
const hash=file=>crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');
function read(file){const b=fs.readFileSync(file);return b[0]===255&&b[1]===254?b.subarray(2).toString('utf16le'):b.toString('utf8').replace(/^\uFEFF/,'');}
const load=file=>JSON.parse(read(file));
const common=git('rev-parse','--path-format=absolute','--git-common-dir');
const receipt=name=>path.join(common,'wa-recovery-evidence',name,'report.json');
const own=[['native-source','wa-native-browser-i1Nstv',76],['native-embedded','wa-native-browser-eN3Moi',76],['adversarial','wa-native-browser-9PJd9j',78],['recovery-initial','wa-two-window-XtL4kt',null],['recovery-rerun','wa-two-window-Dft7Ev',22],['fallback-causality','wa-native-browser-GLFho8',78]];
const checks=own.map(([name,root,count])=>{
 const file=receipt(root),r=load(file);if(count!==null){assert.ok(r.passed);assert.equal(r.checks.length,count);}
 assert.ok(r.cleanup.fixture_home_removed);
 assert.ok(r.cleanup.ownedPids.every(p=>p.exited&&p.job.creation_proven&&p.job.assigned&&p.job.in_job&&p.job.kill_on_close&&p.job.no_breakaway&&p.job.limit_flags===8192&&p.job.drained&&p.job.accounting.active_processes===0));
 fs.writeFileSync(path.join(dir,name+'.receipt.json'),JSON.stringify(r,null,2)+'\n');
 return {name,passed:r.passed,checks:r.checks.length,skipped:0,raw:file,raw_sha256:hash(file),error:r.error||null,cleanupVerified:true};
});
const producerFile=path.join(common,'wa-ui-native-delivery','18bc6bf05be9cdbd01a1e50a6a520e0e9e9a499b','report.json');
const mutationsFile=path.join(common,'wa-native-mutations','5f885df5-2ecb-432e-8b24-00928ef433de','report.json');
const mutations=load(mutationsFile);
for(const m of mutations.mutations){assert.ok(read(m.log).includes(m.assertion));m.log_sha256=hash(m.log);}
assert.equal(mutations.mutations.length,5);assert.ok(mutations.restored);
fs.writeFileSync(path.join(dir,'producer-mutations-inspected.json'),JSON.stringify(mutations,null,2)+'\n');
const adversarial=load(receipt('wa-native-browser-9PJd9j'));
assert.equal(adversarial.review.fallback.terminalState,'completed');assert.equal(adversarial.review.fallback.mainAfter,false);assert.equal(adversarial.review.fallback.pane.terminal,false);assert.equal(adversarial.review.fallback.fresh.terminal,true);
const build=load(path.join(dir,'build.json'));
require(path.join(repo,'scripts/native-child-build-proof.cjs')).verify(repo,build.binary,path.join(dir,'build.json'));
for(const name of ['ui','high-http']){const job=load(path.join(dir,name+'-job.json'));assert.ok(job.creation_proven&&job.assigned&&job.in_job&&job.no_breakaway&&job.kill_on_close&&job.drained&&job.accounting.active_processes===0&&job.native_exit===0);}
const report={schema:1,kind:'independent-source-review-not-admission',verdict:'request_changes',producer:{head:'18bc6bf05be9cdbd01a1e50a6a520e0e9e9a499b',tree:'8bd76bc322d2aebed1ffa4045f4945ea144ab9de',prototype:'98e14c5ccd87a37865de7fb6ce6673d60c90ded7',report:producerFile,report_sha256:hash(producerFile)},review:{branch:git('branch','--show-current'),custodyMerge:git('rev-parse','HEAD'),custodyTree:git('rev-parse','HEAD^{tree}'),session:process.env.CODEX_THREAD_ID,terminal:'term_3f65c45a-b412-41ed-b814-5b3ca0f95894',task:'task_fe9bf9750138',dispatch:'ctx_92bc7933bf52',sourceChanged:false,originMain:git('rev-parse','origin/main'),behind:Number(git('rev-list','--count','HEAD..origin/main')),mergeTree:git('merge-tree','--write-tree','origin/main','HEAD')},build:{binary:build.binary,sha256:build.binary_sha256,receipt:'build.json',jobs:2},checks,
 findings:[{priority:'P2',location:'ui/app.js:4833 and 4908',title:'An unavailable native journal blocks durable terminal fallback on existing views',proof:'adversarial.receipt.json review.fallback',causality:'fallback-causality.json',effect:'Completed answer stays absent on main chat and previously attached pane despite available complete session rows; fresh mount shows answer. Subsequent native poll failures return true and do not reach normal ledger follow.'},{priority:'P3',location:'lua/core/subagents.lua:760',title:'Malformed supplied native cursors silently become zero',proof:'adversarial.receipt.json review.cursor',effect:'garbage, object and true cursors return ok=true rather than invalid_native_event_cursor; negative, fractional and unsafe numeric string do refuse. Ownership is still enforced; no foreign disclosure was observed.'}],
 selectedRust:{native:{passed:20,failed:0,ignored:0,filtered:63,log:'rust-native.log'},httpJournal:{passed:2,failed:0,ignored:0,filtered:81,log:'rust-http-journal.log'}},highHttp:{passed:36,skipped:0,log:'high-http.log'},runKeyUi:{passed:10,skipped:0,scope:'exact helper contract only'},directUi:{passed:true,stages:['reload','startup-recovery','inspect-window','view-window'],log:'ui.log',job:'ui-job.json'},producerMutations:mutations,independentGuardMutations:load(path.join(dir,'guard-mutations.json')),
 historyCorrection:{identicalTreeAndParents:git('show','-s','--format=%T %P','b395de242034e589edc5da079b02a468819ac04f')===git('show','-s','--format=%T %P','16310ade77d66482c825355fb2874c075fc4c9c5'),originalPrototypePreserved:spawnSync('git',['merge-base','--is-ancestor','98e14c5ccd87a37865de7fb6ce6673d60c90ded7','HEAD'],{cwd:repo}).status===0},
 limits:['No full application gate or source acceptance/admission was authored; sole acceptance/merge lane ctx50 determines current admission-required proof.','Old recovery initial native-pane timeout was read_capacity_busy; rerun passed22. Reserved later background completion/read-control and failed-task continuation changes were not implemented.','Native restart checks compare a first256 archived-event page and recover the full terminal answer in the browser; no all-archive-throughout-restart equivalence or production crash-power-loss proof is claimed.','Direct UI preserves original assertions and page inspect/profile/reuse behavior; no real wa-window lifecycle/install/deploy was exercised.','Fixture homes/DBs/repos/provider endpoints/ports/browser profiles were private. Windows Job receipts prove creation, queried kill-on-close/no-breakaway, membership and active0 drain; they are not an administrator-proof sandbox.','FULL synchronous per-event SQLite and global native task mutex can serialize writes; storage/history rendering grows without pruning. No performance default or throughput gain is inferred.','Raw content persists in journal/ledger; UI stripThinking still trims display-edge whitespace.','No production resources, account/provider config, node/window or paid inference were used.'],gate_verified:false,admission_verified:false,source_acceptance_authored:false,main_moved:false,deployed:false};
assert.equal(report.review.custodyTree,report.producer.tree);assert.ok(report.historyCorrection.identicalTreeAndParents&&report.historyCorrection.originalPrototypePreserved);
fs.writeFileSync(path.join(dir,'report.json'),JSON.stringify(report,null,2)+'\n');
// Artifact text follows the repo LF contract; normalize only this review directory.
for(const entry of fs.readdirSync(dir)){const file=path.join(dir,entry);if(/\.(json|log|ps1|cjs|md)$/.test(entry))fs.writeFileSync(file,read(file).replace(/\r\n/g,'\n'),'utf8');}
console.log('Independent exact-tip source review report assembled and receipt invariants verified');
