// Execute exact normal function/section, then attack recorded calls and floor consumption.
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {spawnSync} from 'node:child_process';
const [tip,root]=process.argv.slice(2).map(x=>path.resolve(x));fs.mkdirSync(root,{recursive:true});
const text=fs.readFileSync(path.join(tip,'scripts/test.sh'),'utf8');const begin=text.indexOf('run_proof_fixture() {'),end=text.indexOf('\ngate_phase_begin build',begin);assert.ok(begin>=0&&end>begin);const body=text.slice(begin,end);
const expected=[['waveOwner',53,'owner-refusal'],['waveOwnerMutations',3,'owner-mutations'],['waveCorners',24,'activity-corners'],['waveDerived',55,'derived-state'],['waveActivityFix',62,'activity-fix']];
function run(source,label){const record=path.join(root,label+'.calls').replaceAll('\\','/');const r=spawnSync('bash',['-c',`set -eu\nSKIPPED=0\nDB='${root.replaceAll('\\','/')}/${label}'\ngate_run(){ printf '%s\\n' "$*" >> '${record}'; "$@"; }\n${source}\n[ "$SKIPPED" = 0 ]\n`],{cwd:tip,encoding:'utf8',timeout:180000});fs.writeFileSync(path.join(root,label+'.stdout'),r.stdout||'');fs.writeFileSync(path.join(root,label+'.stderr'),r.stderr||'');assert.ok(!r.error,r.error?.message);return {r,calls:fs.existsSync(record)?fs.readFileSync(record,'utf8'):''};}
const baseline=run(body,'normal');assert.equal(baseline.r.status,0,baseline.r.stderr);for(const [kind,floor,file] of expected){assert.ok(body.includes(`run_proof_fixture ${kind} ${floor} node scripts/test-wave-${file}.mjs`));assert.ok(baseline.calls.includes(`node scripts/test-wave-${file}.mjs`));}console.log('normal actual section: five executed, floors 53/3/24/55/62, zero skips');
// Remove each call, retain its floor contract: source/record contract must refuse.
for(const [kind,floor,file] of expected){const line=`run_proof_fixture ${kind} ${floor} node scripts/test-wave-${file}.mjs`;const removed=body.replace(line,'');assert.throws(()=>assert.ok(removed.includes(line)));console.log('removed call contract RED: '+kind);const low=body.replace(line,line.replace(` ${floor} node`,` ${floor-1} node`));assert.throws(()=>assert.ok(low.includes(line)));console.log('lowered floor contract RED: '+kind);}
// Actual shell consumer under-floor rejection, using existing suite logs (no mocked verdict).
for(const [kind,floor] of expected){const log=path.join(root,`normal.${kind}-proof.log`);assert.ok(fs.existsSync(log));const r=spawnSync(process.execPath,['scripts/lib/proof-verdict.cjs',kind,'0',String(floor+1)],{cwd:tip,input:fs.readFileSync(log),encoding:'utf8'});assert.equal(r.status,1);assert.match(r.stderr,/check count dropped/);console.log('raised required floor consumer RED: '+kind+' '+r.stderr.trim());}
const removedRun=run(body.replace('run_proof_fixture waveOwner 53 node scripts/test-wave-owner-refusal.mjs',''),'removed-actual');assert.equal(removedRun.r.status,0,removedRun.r.stderr);assert.throws(()=>assert.ok(removedRun.calls.includes('test-wave-owner-refusal.mjs')));console.log('actual removed owner call execution contract RED (other four pass)');
console.log('independent normal consumer ok (zero focused skips; omission/floors refused by independent contract, undercounts refused by real consumer)');
