local json=dofile('lua/vendor/json.lua')
local memory=dofile('lua/core/memory.lua');memory.setup()
local agent=dofile('lua/core/agent.lua')
local spells=dofile('lua/core/spells.lua')
local sid=memory.start_session('','fresh',{user_id='master'})
local bot=agent.new(sid,function() end,'master','master','')
local before=bot:build_context()[1].content
assert(before:find('gpt-6-luna',1,true) and before:find('Astra is reserved',1,true),'fresh session carries model routing policy')
assert(before:find('Delegate substantial implementation',1,true),'fresh session delegates without memory')
assert(before:find('one bounded improvement task',1,true),'feedback loop has explicit instruction bound')
local result=spells.save({name='unused-fixture-spell',steps={{kind='run',script="printf '{\"ok\":true}'"}},post={{kind='run',script="printf '{\"ok\":true}'",expect={ok=true}}}})
assert(not result.error,json.encode(result))
local after=bot:build_context()[1].content
assert(before==after and not after:find('unused-fixture-spell',1,true),'unused spell adds zero bootstrap bytes')
print('orchestrator defaults ok (fresh-session routing, bounded feedback policy, zero unused-spell prefix growth)')
