local json=dofile('lua/vendor/json.lua')
local memory=dofile('lua/core/memory.lua');memory.setup()
local agent=dofile('lua/core/agent.lua')
local spells=dofile('lua/core/spells.lua')
local sid=memory.start_session('','fresh',{user_id='master'})
local bot=agent.new(sid,function() end,'master','master','')
local before=bot:build_context()[1].content
assert(before:find('No subagents in direct mode',1,true),'fresh session stays direct without opt-in')
assert(before:find('/orchestration',1,true),'explicit mode contract is discoverable without memory')
assert(before:find('Only the coordinator',1,true) and before:find('report',1,true),'installation ownership and report-driven followups are explicit')
local result=spells.save({name='unused-fixture-spell',steps={{kind='run',script="printf '{\"ok\":true}'"}},post={{kind='run',script="printf '{\"ok\":true}'",expect={ok=true}}}})
assert(not result.error,json.encode(result))
local after=bot:build_context()[1].content
assert(before==after and not after:find('unused-fixture-spell',1,true),'unused spell adds zero bootstrap bytes')
print('orchestrator defaults ok (direct default, explicit routing opt-in, coordinator update ownership, zero unused-spell prefix growth)')
