local json=dofile('lua/vendor/json.lua')
local memory=dofile('lua/core/memory.lua')
local workspaces=dofile('lua/core/workspaces.lua')
local resources=dofile('lua/core/resources.lua')
local paths=dofile('lua/core/paths.lua')
local tools=dofile('lua/core/tools.lua')
local checks=0
local function check(value,label) assert(value,label);checks=checks+1 end
local source_path=host.getenv('WASM_AGENT_TEST_SOURCE')
local parent=memory.start_session('local','release-parent',{id='release-parent',user_id='owner',node_id='test-node'})
memory.set_session_worktree(parent,source_path)
local id=memory.start_session('local','subagent',{id='release-target',user_id='owner',node_id='test-node',parent_session_id=parent,workspace_required=true})
local workspace,why=workspaces.ensure(memory,id,parent)
check(workspace~=nil,'allocate cleanup target: '..tostring(why))
local denied,denial=workspaces.release(memory,id,'other')
check(not denied and denial=='forbidden','other principal cannot remove workspace')
local running={user_id='owner',session_id=id,run_id='release-running'}
check(resources.begin(running).ok,'participating run owns session')
local busy,busy_why=workspaces.release(memory,id,'owner')
check(not busy and busy_why=='resource_busy','active session cannot be cleaned')
resources.finish(running)
host.write_file(workspace.worktree..'/keep.txt','uncommitted evidence')
local dirty,dirty_why=workspaces.release(memory,id,'owner')
check(not dirty and dirty_why=='workspace_release_dirty_or_ignored_files','uncommitted files refuse cleanup')
check(host.read_file(workspace.worktree..'/keep.txt')=='uncommitted evidence','refused cleanup preserves file')
assert(os.remove(workspace.worktree..'/keep.txt'))
host.write_file(workspace.worktree..'/.gitignore','ignored.txt\n')
host.write_file(workspace.worktree..'/ignored.txt','ignored evidence')
local ignored,ignored_why=workspaces.release(memory,id,'owner')
check(not ignored and ignored_why=='workspace_release_dirty_or_ignored_files','ignored files refuse cleanup too')
assert(os.remove(workspace.worktree..'/.gitignore'));assert(os.remove(workspace.worktree..'/ignored.txt'))
local saved=workspace.worktree
workspace.worktree=source_path
memory.set_session_workspace(id,workspace)
local escaped,escape_why=workspaces.release(memory,id,'owner')
check(not escaped and escape_why=='workspace_release_binding_mismatch','tampered path cannot remove source')
workspace.worktree=saved;memory.set_session_workspace(id,workspace)
-- Release consumes only the bounded host projection, never scans historical files.
local original_operation=host.operation
local observed_cwd
host.operation=function(action,args)
  if action=='relevant' then
    local request=json.decode(args);observed_cwd=request.cwd
    check(request.limit==1,'release asks for one unresolved blocker')
    return json.encode({ok=true,operations={{operation_id='op-fixture-unresolved'}}})
  end
  return original_operation(action,args)
end
local uncertain,uncertain_why=workspaces.release(memory,id,'owner')
check(not uncertain and uncertain_why=='workspace_release_operation_unresolved:op-fixture-unresolved','unknown relevant operation blocks removal')
check(observed_cwd==host.canonical_path(saved),'lookup uses actual canonical target')
host.operation=function(action,args)
  if action=='relevant' then return json.encode({ok=false,error='operation_index_import_required'}) end
  return original_operation(action,args)
end
local unreadable,unreadable_why=workspaces.release(memory,id,'owner')
check(not unreadable and unreadable_why:find('workspace_release_operations_unavailable:',1,true)==1,'unavailable or incomplete index blocks removal')
host.operation=original_operation
local released,release_why=workspaces.release(memory,id,'owner')
check(released and released.state=='released','clean inactive worktree released: '..tostring(release_why))
check(host.canonical_path(saved)==nil,'released directory is gone')
local branch=json.decode(host.exec('git show-ref --verify refs/heads/'..workspace.branch,source_path,30))
check(branch.code==0,'branch and commits remain reachable')
check(workspaces.release(memory,id,'owner').state=='released','repeat release is idempotent')
local again,again_why=workspaces.ensure(memory,id,parent)
check(not again and again_why=='workspace_released_or_release_unresolved','released worktree is not silently reallocated')
local write=tools.dispatch(memory,'write',{path='after.txt',content='no fallback'},'master',{user_id='owner',session_id=id,changes={}})
check(write.error=='session_workspace_unavailable' and host.read_file(source_path..'/after.txt')==nil,'released session cannot write into source fallback')
local committed=memory.start_session('local','subagent',{id='release-unmerged',user_id='owner',node_id='test-node',parent_session_id=parent,workspace_required=true})
local cw=assert(workspaces.ensure(memory,committed,parent))
host.write_file(cw.worktree..'/unmerged.txt','committed evidence')
local commit=json.decode(host.exec('git add unmerged.txt && git commit -m fixture',cw.worktree,30))
check(commit.code==0,'create unmerged committed work')
local unmerged,unmerged_why=workspaces.release(memory,committed,'owner')
check(not unmerged and unmerged_why=='workspace_release_unmerged_commits','unmerged commits block removal')
check(host.read_file(cw.worktree..'/unmerged.txt')=='committed evidence','unmerged worktree retained')
local interrupted=memory.start_session('local','subagent',{id='release-interrupted',user_id='owner',node_id='test-node',parent_session_id=parent,workspace_required=true})
local iw=assert(workspaces.ensure(memory,interrupted,parent))
iw.state='releasing';memory.set_session_workspace(interrupted,iw)
local removed=json.decode(host.exec('git worktree remove "'..iw.worktree..'"',source_path,30))
check(removed.code==0,'simulate lost successful removal receipt in disposable managed tree')
local reconciled=workspaces.release(memory,interrupted,'owner')
check(reconciled and reconciled.state=='released','missing registered tree reconciles lost removal receipt')
local missing=memory.start_session('local','subagent',{id='release-missing',user_id='owner',node_id='test-node',parent_session_id=parent,workspace_required=true})
local mw=assert(workspaces.ensure(memory,missing,parent))
local no_evidence,no_evidence_why=workspaces.reconcile_release(memory,missing,'owner','')
check(not no_evidence and no_evidence_why=='workspace_reconcile_evidence_required','missing binding reconciliation requires explicit effect evidence')
local exists,exists_why=workspaces.reconcile_release(memory,missing,'owner','inspected fixture')
check(not exists and exists_why=='workspace_reconcile_tree_present_or_unverifiable','existing tree cannot be relabeled released')
check(json.decode(host.exec('git worktree remove "'..mw.worktree..'"',source_path,30)).code==0,'simulate missing directory with allocated binding in private fixture')
local live={user_id='owner',session_id=missing,run_id='missing-live-owner'}
check(resources.begin(live).ok,'own missing session before reconciliation')
local held,held_why=workspaces.reconcile_release(memory,missing,'owner','inspected fixture')
check(not held and held_why=='resource_busy','active owner blocks missing-directory reconciliation')
resources.finish(live)
local reconciled_missing,missing_why=workspaces.reconcile_release(memory,missing,'owner','Git removal observed, branch integrated and operation effects settled')
check(reconciled_missing and reconciled_missing.state=='released','allocated missing-directory binding reconciles: '..tostring(missing_why))
check(reconciled_missing.start_state.release_reconciliation.evidence~='','reconciliation evidence is durable')
local parked_id=memory.start_session('local','subagent',{id='release-parked',user_id='owner',node_id='test-node',parent_session_id=parent,workspace_required=true})
local pw=assert(workspaces.ensure(memory,parked_id,parent))
local attached,attached_why=workspaces.reconcile_park(memory,parked_id,'owner',pw.base_commit,'inspected retained terminal')
check(not attached and attached_why=='workspace_park_not_detached_or_unverifiable','attached tree cannot be relabeled parked')
check(json.decode(host.exec('git switch --detach '..pw.base_commit,pw.worktree,30)).code==0,'detach only private finished fixture')
local parked,park_why=workspaces.reconcile_park(memory,parked_id,'owner',pw.base_commit,'owner settled, exact integrated detached tip inspected')
check(parked and parked.state=='parked' and parked.branch=='','parked binding agrees with detached Git state: '..tostring(park_why))
local allocate_parked,allocate_why=workspaces.ensure(memory,parked_id,parent)
check(not allocate_parked and allocate_why=='workspace_released_or_release_unresolved','parked finished workspace cannot silently allocate another feature branch')
print('workspace release ok ('..checks..' checks)')
