local json = dofile("lua/vendor/json.lua")
local memory = dofile("lua/core/memory.lua")
local checks = 0
local function ok(value, label)
  checks = checks + 1
  if not value then error(label) end
end
local function rejected(source, seq, owner, expected)
  local id, why = memory.fork_session(source, seq, owner)
  ok(id == nil and why == expected, "expected " .. expected .. ", got " .. tostring(id) .. "/" .. tostring(why))
end
memory.setup()
local source = memory.start_session("local", "chat", {user_id="owner",node_id="node",title="source"})
memory.set_session_summary(source, 0, "LOSSY SUMMARY MUST NOT CROSS FORK")
memory.set_session_worktree(source, "parent-checkout")
memory.append_turn(source, {role="user",content="first question"})
memory.append_turn(source, {role="assistant",content="first answer"})
memory.append_turn(source, {role="user",content="tool request"})
memory.append_turn(source, {role="assistant",content="calling tool",tool_calls={{id="call-1",type="function",["function"]={name="bash",arguments="{}"}}}})
memory.append_turn(source, {role="tool",content="tool output",tool_call_id="call-1",tool_name="bash"})
memory.append_turn(source, {role="assistant",content="after tool"})
memory.append_turn(source, {role="user",content="later, do not copy"})
local fork, why = memory.fork_session(source, 6, "owner")
ok(type(fork)=="string" and not why, "valid exact fork: " .. tostring(why))
local child = memory.session(fork)
ok(child.fork_parent_id==source and child.fork_parent_seq==6, "durable exact ancestry")
ok(child.parent_session_id==nil, "conversation fork remains distinct from delegated child")
ok(child.summary=="" and child.summarized_until==0, "no post-fork summary/watermark leakage")
ok(child.worktree=="", "fork does not inherit mutable workspace")
local copied = memory.session_messages(fork, {all=true})
ok(#copied==6 and copied[6].content=="after tool", "only exact non-summary ancestry copied")
ok(copied[4].tool_calls[1].id=="call-1" and copied[5].tool_call_id=="call-1", "complete tool call/result retained")
ok(memory.message_count(source)==7, "source transcript remains unchanged")
ok(not child.summary:find("LOSSY SUMMARY",1,true), "compacted source summary is not copied")
rejected(source, 7, "other-owner", "forbidden")
rejected(source, 99, "owner", "invalid_boundary")
local incomplete = memory.start_session("local", "chat", {user_id="owner",node_id="node"})
memory.append_turn(incomplete,{role="user",content="ask"})
memory.append_turn(incomplete,{role="assistant",content="call",tool_calls={{id="unsettled",type="function",["function"]={name="bash",arguments="{}"}}}})
rejected(incomplete,2,"owner","incomplete_tool_exchange")
rejected(incomplete,0,"owner","invalid_boundary")
host.sql_exec("DELETE FROM messages WHERE session_id=?", json.encode({source}))
ok(#memory.session_messages(fork,{all=true})==6, "fork evidence survives source retention/deletion")
print("session fork ok (" .. checks .. " checks)")
