local json=dofile('lua/vendor/json.lua')
local memory=dofile('lua/core/memory.lua')
local workspaces=dofile('lua/core/workspaces.lua')
local resources=dofile('lua/core/resources.lua')
local paths=dofile('lua/core/paths.lua')
local tools=dofile('lua/core/tools.lua')
local checks=0
local function check(value,label) assert(value,label);checks=checks+1 end
local source_path=host.getenv('WASM_AGENT_TEST_SOURCE')
local parent=memory.start_session('local','release-parent',{id='release-parent',user_id='owner',node_id='test-node'})
memory.set_session_worktree(parent,source_path)
local id=memory.start_session('local','subagent',{id='release-target',user_id='owner',node_id='test-node',parent_session_id=parent,workspace_required=true})
local workspace,why=workspaces.ensure(memory,id,parent)
check(workspace~=nil,'allocate cleanup target: '..tostring(why))
local denied,denial=workspaces.release(memory,id,'other')
check(not denied and denial=='forbidden','other principal cannot remove workspace')
local running={user_id='owner',session_id=id,run_id='release-running'}
check(resources.begin(running).ok,'participating run owns session')
local busy,busy_why=workspaces.release(memory,id,'owner')
check(not busy and busy_why=='resource_busy','active session cannot be cleaned')
resources.finish(running)
host.write_file(workspace.worktree..'/keep.txt','uncommitted evidence')
local dirty,dirty_why=workspaces.release(memory,id,'owner')
check(not dirty and dirty_why=='workspace_release_dirty_or_ignored_files','uncommitted files refuse cleanup')
check(host.read_file(workspace.worktree..'/keep.txt')=='uncommitted evidence','refused cleanup preserves file')
assert(os.remove(workspace.worktree..'/keep.txt'))
host.write_file(workspace.worktree..'/.gitignore','ignored.txt\n')
host.write_file(workspace.worktree..'/ignored.txt','ignored evidence')
local ignored,ignored_why=workspaces.release(memory,id,'owner')
check(not ignored and ignored_why=='workspace_release_dirty_or_ignored_files','ignored files refuse cleanup too')
assert(os.remove(workspace.worktree..'/.gitignore'));assert(os.remove(workspace.worktree..'/ignored.txt'))
local saved=workspace.worktree
workspace.worktree=source_path
memory.set_session_workspace(id,workspace)
local escaped,escape_why=workspaces.release(memory,id,'owner')
check(not escaped and escape_why=='workspace_release_binding_mismatch','tampered path cannot remove source')
workspace.worktree=saved;memory.set_session_workspace(id,workspace)
local opdir=paths.data()..'/operations/fixture-unresolved'
host.write_file(opdir..'/state.json',json.encode({settled=false,cleanup='unknown'}))
local uncertain,uncertain_why=workspaces.release(memory,id,'owner')
check(not uncertain and uncertain_why=='workspace_release_operation_unresolved:fixture-unresolved','unknown operation blocks removal')
host.write_file(opdir..'/state.json',json.encode({settled=true,cleanup='terminated'}))
local original_list=host.list_dir
host.list_dir=function(path)
  if path==paths.data()..'/operations' then return json.encode({entries={{name='unreadable',kind='other'}}}) end
  return original_list(path)
end
local unreadable,unreadable_why=workspaces.release(memory,id,'owner')
host.list_dir=original_list
check(not unreadable and unreadable_why=='workspace_release_operation_unreadable:unreadable','unreadable operation entry blocks removal')
local released,release_why=workspaces.release(memory,id,'owner')
check(released and released.state=='released','clean inactive worktree released: '..tostring(release_why))
check(host.canonical_path(saved)==nil,'released directory is gone')
local branch=json.decode(host.exec('git show-ref --verify refs/heads/'..workspace.branch,source_path,30))
check(branch.code==0,'branch and commits remain reachable')
check(workspaces.release(memory,id,'owner').state=='released','repeat release is idempotent')
local again,again_why=workspaces.ensure(memory,id,parent)
check(not again and again_why=='workspace_released_or_release_unresolved','released worktree is not silently reallocated')
local write=tools.dispatch(memory,'write',{path='after.txt',content='no fallback'},'master',{user_id='owner',session_id=id,changes={}})
check(write.error=='session_workspace_unavailable' and host.read_file(source_path..'/after.txt')==nil,'released session cannot write into source fallback')
local committed=memory.start_session('local','subagent',{id='release-unmerged',user_id='owner',node_id='test-node',parent_session_id=parent,workspace_required=true})
local cw=assert(workspaces.ensure(memory,committed,parent))
host.write_file(cw.worktree..'/unmerged.txt','committed evidence')
local commit=json.decode(host.exec('git add unmerged.txt && git commit -m fixture',cw.worktree,30))
check(commit.code==0,'create unmerged committed work')
local unmerged,unmerged_why=workspaces.release(memory,committed,'owner')
check(not unmerged and unmerged_why=='workspace_release_unmerged_commits','unmerged commits block removal')
check(host.read_file(cw.worktree..'/unmerged.txt')=='committed evidence','unmerged worktree retained')
local interrupted=memory.start_session('local','subagent',{id='release-interrupted',user_id='owner',node_id='test-node',parent_session_id=parent,workspace_required=true})
local iw=assert(workspaces.ensure(memory,interrupted,parent))
iw.state='releasing';memory.set_session_workspace(interrupted,iw)
local removed=json.decode(host.exec('git worktree remove "'..iw.worktree..'"',source_path,30))
check(removed.code==0,'simulate lost successful removal receipt in disposable managed tree')
local reconciled=workspaces.release(memory,interrupted,'owner')
check(reconciled and reconciled.state=='released','missing registered tree reconciles lost removal receipt')
print('workspace release ok ('..checks..' checks)')
