local json=dofile("lua/vendor/json.lua")
local memory=dofile("lua/core/memory.lua")
local tools=dofile("lua/core/tools.lua")
local platform=dofile("lua/core/platform.lua")
local session_id=host.getenv("WASM_AGENT_TEST_SESSION")
local content=host.getenv("WASM_AGENT_TEST_CONTENT")
assert(session_id and content,"workspace worker needs session and content")
memory.setup()
local workspace=memory.session_workspace(session_id)
assert(workspace and workspace.required and workspace.state=="allocated" and workspace.worktree~="","worker refuses missing binding")
local delay=host.exec(platform.os()=="windows" and "ping -n 2 127.0.0.1 >NUL" or "sleep 1",workspace.worktree,5)
local result=tools.dispatch(memory,"write",{path="concurrent.txt",content=content},"master",{session_id=session_id,user_id="owner",changes={files={}}})
assert(result.ok,"concurrent session write failed: "..json.encode(result))
print("workspace worker wrote "..session_id)
